[package]
name = "divotty-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
rand.workspace = true
rand_pcg.workspace = true

[dev-dependencies]
# tests unitaires du moteur de résolution de coup
